CREATE TABLE TB_HOSPEDE( 
    CPF VARCHAR2(14),
    NOME VARCHAR2(50) CONSTRAINT TB_HOSPEDE_NOME_NN NOT NULL,
    EMAIL VARCHAR2(50) CONSTRAINT TB_HOSPEDE_EMAIL_UN UNIQUE,
    TELEFONE VARCHAR2(11) CONSTRAINT TB_HOSPEDE_TELEFONE_NN NOT NULL,
    USUARIO VARCHAR2(50) CONSTRAINT TB_HOSPEDE_USUARIO_UN UNIQUE,
    DATA_NASC VARCHAR2(10) CONSTRAINT TB_HOSPEDE_DATA_NASC_NN NOT NULL,
    SENHA VARCHAR2(16) CONSTRAINT TB_HOSPEDE_SENHA_NN NOT NULL, 
    CONSTRAINT TB_HOSPEDE_CPF_PK PRIMARY KEY (CPF)
);

CREATE TABLE TB_GARAGEM (
    NUM_GARAGEM NUMBER(4),
    TIPO_GARAGEM VARCHAR2(20) CONSTRAINT TIPO_GARAGEM_NN NOT NULL,
    CONSTRAINT NUM_GARAGEM_PK PRIMARY KEY (NUM_GARAGEM)
);

CREATE TABLE TB_VISITANTE (
    CPF_VISITANTE VARCHAR2(14), 
    NOME_VISITANTE VARCHAR2(50) CONSTRAINT TB_VISITANTE_NOME_VISITANTE_NN NOT NULL,
    HORA_ENTRADA VARCHAR2(5) CONSTRAINT TB_VISITANTE_HORA_ENTRADA_NN NOT NULL,
    HORA_SAIDA VARCHAR2(5) CONSTRAINT TB_VISTANTE_HORA_SAIDA_NN NOT NULL,
    CONSTRAINT TB_VISITANTE_CPF_PK PRIMARY KEY (CPF_VISITANTE)
);

CREATE TABLE TB_QUARTO( 
    NUM_QUARTO NUMBER(4),
    TIPO_QUARTO VARCHAR2(100) CONSTRAINT TB_QUARTO_TIPO_QUARTO_NN NOT NULL,
    DESCRICAO_QUARTO VARCHAR2(1000) CONSTRAINT TB_QUARTO_DESCRICAO_QUARTO_NN NOT NULL,
    IMG_QUARTO VARCHAR2(100) CONSTRAINT TB_QUARTO_IMG_QUARTO_NN NOT NULL,
    PRECO_QUARTO VARCHAR2(5) CONSTRAINT TB_QUARTO_PRECO_QUARTO_NN NOT NULL,
    CONSTRAINT TB_QUARTO_NUM_QUARTO_PK PRIMARY KEY (NUM_QUARTO)
);

CREATE TABLE TB_RESERVA( 
    CPF VARCHAR2(14),
    NUM_QUARTO NUMBER(4),
    CPF_VISITANTE VARCHAR2(15),
    NUM_GARAGEM NUMBER(4),
    DATA_CHECKIN VARCHAR2(10) CONSTRAINT TB_RESERVA_DATA_CHECKIN_NN NOT NULL,
    HORA_CHECKIN VARCHAR2(5) CONSTRAINT TB_RESERVA_HORA_CHECKIN_NN NOT NULL,
    DATA_CHECKOUT VARCHAR2(10) CONSTRAINT TB_RESERVA_DATA_CHECKOUT_NN NOT NULL,
    HORA_CHECKOUT VARCHAR2(5) CONSTRAINT TB_RESERVA_HORA_CHECKOUT_NN NOT NULL,
    CONSTRAINT TB_RESERVA_RESERVANDO_PK PRIMARY KEY (CPF, NUM_QUARTO),
    CONSTRAINT TB_RESERVA_CPF_FK FOREIGN KEY (CPF) REFERENCES TB_HOSPEDE (CPF),
    CONSTRAINT TB_RESERVA_NUM_QUARTO_FK FOREIGN KEY (NUM_QUARTO) REFERENCES TB_QUARTO (NUM_QUARTO),
    CONSTRAINT TB_RESERVA_CPF_VISITANTE_FK FOREIGN KEY (CPF_VISITANTE) REFERENCES TB_VISITANTE (CPF_VISITANTE),
    CONSTRAINT TB_RESERBA_NUM_GARAGEM_FK FOREIGN KEY (NUM_GARAGEM) REFERENCES TB_GARAGEM (NUM_GARAGEM)
);


CREATE TABLE TB_DEMONSTRATIVO(
    SERVICOS_HOTEL VARCHAR2(30) CONSTRAINT SERVICO_HOTEL_PK PRIMARY KEY
);


-- População das informações dos hospedes. -- CPF, NOME, EMAIL, TELEFONE, USUARIO, DATA_NASC, SENHA

INSERT INTO TB_HOSPEDE VALUES ('111.333.444-55', 'Ronaldo Sousa', 'ronald_sousa@gmail.com', '11946523555', 'ronaldo_sousa', '30/04/1970', 'ronaldo1234');
INSERT INTO TB_HOSPEDE VALUES ('123.456.789-99', 'Vitoria Oliveira', 'vitoria_oliveira@hotmail.com', '21956665487', 'vitoria_oliveira', '21/01/2001', 'vitoria4321');
INSERT INTO TB_HOSPEDE VALUES ('444.555.666-77', 'Leonardo Santos', 'leonardo_santos@gmail.com', '11933325658', 'leonardo_santos', '05/05/1999', 'leonardo1234');

-- População das informações dos visitantes. -- CPF_VISITANTE, NOME_VISITANTE, HORA_ENTRADA, HORA_SAIDA
INSERT INTO TB_VISITANTE VALUES ( '123.456.789-01', 'Fernando Sousa', '10:00', '15:00');
INSERT INTO TB_VISITANTE VALUES ( '111.222.333-44', 'Fernanda Golsaves', '11:00', '15:00');
INSERT INTO TB_VISITANTE VALUES ( '555.666.777-88', 'Gustavo Rossi', '10:00', '17:00');

-- Poúlação das informações dos quartos. -- NUM_QUARTO, TIPO_QUARTO, DESCRICAO_QUARTO, IMG_QUARTO, PRECO_QUARTO
INSERT INTO TB_QUARTO VALUES ('0001', 'Quarto Individual', 'Quarto para uma só pessoa, com uma cama
individual. Dependendo do requinte do hotel, a área do quarto poderá variar entre
8 e 14 metros quadrados.', 'semIMG', '200');

INSERT INTO TB_QUARTO VALUES (0010, 'Quarto duplo para uso individual', 'Quarto para uma pessoa, com duas
camas.', 'semIMG', '250');

INSERT INTO TB_QUARTO VALUES (0020, 'Quarto Duplo ou Twin', 'Quarto para duas pessoas. O elemento
característico é que este quarto tem duas camas individuais', 'semIMG', '250');

INSERT INTO TB_QUARTO VALUES (0030, 'Quarto Casal', 'Quarto para duas pessoas, mas com
uma cama de casal de tamanho “king”.', 'semIMG', '300');

INSERT INTO TB_QUARTO VALUES (0040, 'Quarto Triplo', 'Quarto para 3 pessoas, normalmente com 3 camas
individuais.uarto para duas pessoas, mas com
uma cama de casal de tamanho “king”.', 'semIMG', '350');

INSERT INTO TB_QUARTO VALUES (0050, 'Quarto Quádruplo', 'Quarto para quatro pessoas',
'semIMG', '400');

INSERT INTO TB_QUARTO VALUES (0060, 'Dormitório', 'É um tipo de quarto com várias camas (normalmente
beliches), que são alugadas por diferentes hóspedes.', 'semIMG', '100');


-- População com as informações das garagens. NUM_GARAGEM, TIPO_GARAGEM.
INSERT INTO TB_GARAGEM VALUES (0001, 'Garagem Preferencial');
INSERT INTO TB_GARAGEM VALUES (0002, 'Garagem Preferencial');
INSERT INTO TB_GARAGEM VALUES (0003, 'Garagem comum');
INSERT INTO TB_GARAGEM VALUES (0004, 'Garagem visitante');

-- Populando com as informações da tb_demonstrativos. servicos_hotel.
INSERT INTO TB_DEMONSTRATIVO VALUES ('Bar');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Restaurante');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Serviço de quarto');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Área de jogos');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Piscina');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Quadra de esportes');
INSERT INTO TB_DEMONSTRATIVO VALUES ('Eventos');


-- População coom as informações das reservas. --CPF, NUM_QUARTO, CPF_VISITANTE, NUM_GARAGEM, DATA_CHECKIN, HORA_CHECKIN, DATA_CHECKOUT, HORA_CHECKOUT.
INSERT INTO TB_RESERVA VALUES ('111.333.444-55', 0001, '123.456.789-01', 0001, '02/10/2022', '10:50', '20/10/2022', '10:50');

